import { money } from '../domain/model.js';

export const exportSectionDefinitions = Object.freeze([
  { id: 'totalSales', title: 'Total Sales' }, { id: 'targetCompletion', title: 'Monthly Target / Completion' },
  { id: 'branchSales', title: 'Branch Sales' }, { id: 'competition', title: 'Competition' },
  { id: 'products', title: 'Product Summary' }, { id: 'packages', title: 'Package Summary' },
  { id: 'cuccio', title: 'Cuccio' }, { id: 'birthday', title: 'Birthday' }
]);
const percent=(current,target)=>target>0?current/target*100:null;
export function buildBossSummary(result,target={overall:0,sutera:0,eco:0},selection=exportSectionDefinitions.map(x=>x.id)){
  if(!result?.range||!result?.totals)throw new Error('A generated dashboard is required.');
  const selected=[...new Set(selection)];if(!selected.length)throw new Error('Please select at least one section to export.');
  const sales=result.totals.sales,sameMonth=result.range.start.slice(0,7)===result.range.end.slice(0,7),t=sameMonth?target:{overall:0,sutera:0,eco:0};
  const branch=(value,targetValue)=>({sales:value,target:targetValue,completion:percent(value,targetValue)});
  return {range:{...result.range},selected,compact:selected.length>=6,partial:(result.sources||[]).some(x=>x.status==='failed')||result.validation?.ok===false,
    sales:{total:sales.total,target:t.overall,completion:percent(sales.total,t.overall),remaining:t.overall>0?Math.max(0,t.overall-sales.total):null,sutera:branch(sales.sutera,t.sutera),eco:branch(sales.eco,t.eco)},
    competition:(result.totals.competition||[]).map(x=>({...x,ranking:(x.ranking||[]).filter(row=>row.rank<=3)})),
    products:result.totals.prettySales?.products||{sutera:{quantity:0,amount:0},eco:{quantity:0,amount:0}},packages:result.totals.prettySales?.packages||{sutera:{quantity:0,amount:0},eco:{quantity:0,amount:0}},cuccio:result.totals.cuccio,birthday:result.totals.birthday};
}
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const qty=v=>new Intl.NumberFormat('en-MY',{maximumFractionDigits:2}).format(Number(v||0));
const fmtDate=v=>new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'numeric',month:'short',year:'numeric'}).format(new Date(`${v}T00:00:00Z`)).toUpperCase();
const pct=v=>v===null?'Target Not Set':`${v.toFixed(2)}%`,bar=v=>v===null?0:Math.min(100,Math.max(0,v));
function competitionHtml(items){const groups=new Map();for(const item of items){const key=`${item.month}|${item.stage}|${item.rangeStart}|${item.rangeEnd}`;(groups.get(key)||groups.set(key,[]).get(key)).push(item);}const names={first:'First Stage',second:'Second Stage',month:'Monthly Summary'};return[...groups].map(([key,entries])=>{const[,stage,start,end]=key.split('|');return`<section class="boss-stage"><header><strong>${names[stage]}</strong><span>${fmtDate(start)} – ${fmtDate(end)}</span></header>${['package','product'].map(type=>`<section class="boss-rank-category"><h4>${type==='package'?'Package':'Product'} Competition</h4><div class="boss-rank-branches">${['Sutera','Eco'].map(branch=>{const entry=entries.find(x=>x.saleType===type&&x.branch===branch),rows=entry?.ranking||[];return`<article class="boss-rank-card ${branch.toLowerCase()}"><h5>${branch.toUpperCase()} TOP 3 RANKS</h5>${rows.length?rows.map(row=>`<div class="boss-rank-row ${row.firstInRank?'rank-group-start':'rank-group-tie'}"><span class="boss-medal-slot">${row.firstInRank?`<b class="boss-medal medal-${row.rank}">${row.rank}</b>`:''}</span><strong>${esc(row.staff)}</strong><span>${qty(row.quantity)}</span><span>${money(row.amount)}</span></div>`).join(''):'<p class="boss-empty">No staff result</p>'}</article>`;}).join('')}</div></section>`).join('')}</section>`;}).join('');}
const productSummary=v=>`<section class="boss-card boss-summary-card boss-product-list"><h3>PRODUCT SUMMARY</h3><div class="boss-summary-branches">${[['sutera','SUTERA'],['eco','ECO']].map(([key,label])=>`<article class="${key}"><small>${label}</small><strong>${qty(v[key].quantity)} items</strong><span>${money(v[key].amount)}</span><div class="boss-item-list">${(v[key].items||[]).map(item=>`<span><b>${esc(item.name)}</b><i>${qty(item.quantity)}</i></span>`).join('')}</div></article>`).join('')}</div></section>`;
const packageSummary=v=>`<section class="boss-card boss-summary-card boss-package-list"><h3>PACKAGE SUMMARY</h3><div class="boss-summary-branches">${[['sutera','SUTERA'],['eco','ECO']].map(([key,label])=>`<article class="${key}"><small>${label}</small><strong>${qty(v[key].quantity)} items</strong><span>${money(v[key].amount)}</span><div class="boss-item-list">${(v[key].items||[]).map(item=>`<span><b>${esc(item.name)}</b><i>${qty(item.quantity)}</i></span>`).join('')}</div></article>`).join('')}</div></section>`;
const customerKpi=(title,v)=>`<section class="boss-card boss-customer-card"><h3>${title}</h3><div><span>Sutera <strong>${qty(v.sutera)}</strong></span><span>Eco <strong>${qty(v.eco)}</strong></span><span class="total">Total <strong>${qty(v.total)}</strong></span></div></section>`;
export function renderBossSummary(model){const has=id=>model.selected.includes(id),out=[];
  if(has('totalSales'))out.push(`<section class="boss-card boss-total"><small>TOTAL SALES</small><strong>${money(model.sales.total)}</strong></section>`);
  if(has('targetCompletion'))out.push(`<section class="boss-card boss-target"><div class="boss-target-ring" style="--progress:${bar(model.sales.completion)}"><span>${model.sales.completion===null?'—':model.sales.completion.toFixed(1)+'%'}</span></div><div><small>MONTHLY TARGET</small><strong>${model.sales.target>0?money(model.sales.target):'Target Not Set'}</strong><p>Completion <b>${pct(model.sales.completion)}</b></p><p>Remaining <b>${model.sales.remaining===null?'—':money(model.sales.remaining)}</b></p></div></section>`);
  if(has('branchSales'))out.push(`<section class="boss-card boss-branches"><article class="sutera"><small>SUTERA</small><strong>${money(model.sales.sutera.sales)}</strong><span>${model.sales.sutera.completion===null?'Target Not Set':model.sales.sutera.completion.toFixed(2)+'% of target'}</span><i><b style="width:${bar(model.sales.sutera.completion)}%"></b></i></article><span class="boss-vs">VS</span><article class="eco"><small>ECO</small><strong>${money(model.sales.eco.sales)}</strong><span>${model.sales.eco.completion===null?'Target Not Set':model.sales.eco.completion.toFixed(2)+'% of target'}</span><i><b style="width:${bar(model.sales.eco.completion)}%"></b></i></article></section>`);
  if(has('competition'))out.push(`<section class="boss-card boss-competition"><h3>COMPETITION · TOP 3 RANKS</h3>${competitionHtml(model.competition)}</section>`);if(has('products'))out.push(productSummary(model.products));if(has('packages'))out.push(packageSummary(model.packages));if(has('cuccio'))out.push(customerKpi('CUCCIO',model.cuccio));if(has('birthday'))out.push(customerKpi('BIRTHDAY',model.birthday));
  return`<article class="boss-summary ${model.compact?'is-compact':''}" data-section-count="${model.selected.length}"><div class="boss-floral left" aria-hidden="true">✦</div><div class="boss-floral right" aria-hidden="true">✦</div><header class="boss-header"><div class="boss-brand"><span>♛</span><strong>PNS</strong><small>PRETTY NAILS SPA</small></div><div><p>PREMIUM PERFORMANCE REPORT</p><h1>WEEKLY DASHBOARD</h1><time>${fmtDate(model.range.start)} – ${fmtDate(model.range.end)}</time></div></header><main class="boss-grid">${out.join('')}</main><footer>PRETTY NAILS SPA · WEEKLY PERFORMANCE</footer></article>`;}
export function bossImageFilename(start,end){const months=['JAN','FEB','MAR','APR','MAY','JUN','JUL','AUG','SEP','OCT','NOV','DEC'],s=start.split('-').map(Number),e=end.split('-').map(Number);return s[0]===e[0]&&s[1]===e[1]?`${s[2]}-${e[2]} ${months[s[1]-1]} BOSS SUMMARY.png`:`${s[2]} ${months[s[1]-1]}-${e[2]} ${months[e[1]-1]} BOSS SUMMARY.png`;}
