import { DashboardDataService } from './services/data-service.js';
import { calculateSales } from './domain/calculation-engine.js';
import { money } from './domain/model.js';
import { TargetRepository } from './repositories/target-repository.js';
import { SectionSettingsRepository } from './repositories/section-settings-repository.js';
import { dashboardModules } from './modules/module-registry.js';
import { readPublicSettings, saveTargets, saveSectionSettings } from './services/cloud-settings-service.js';
import { supabase, requireAdmin } from './services/supabase-service.js';
import { openPrintDialog } from './services/pdf-export.js';

const $ = selector => document.querySelector(selector);
const targets = new TargetRepository(), sections = new SectionSettingsRepository(dashboardModules);
const state = { cache: null, selected: null, sectionSettings: sections.load(), settingsSource: 'cache', generatedRange: null };
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, character => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[character]);
const dateInMalaysia = (offset = 0) => { const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(Date.now()+offset*86400000)).filter(x=>x.type!=='literal').map(x=>[x.type,x.value])); return `${parts.year}-${parts.month}-${parts.day}`; };
const today = dateInMalaysia(), monthStart = `${today.slice(0,7)}-01`;
const formatDate = date => new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'numeric',month:'short',year:'numeric'}).format(new Date(`${date}T00:00:00Z`));
const formatTimestamp = value => new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kuala_Lumpur',day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'}).format(value);
const metricCards = values => ['sutera','eco','total'].map(key=>`<article class="metric-card ${key==='total'?'total':''}"><small>${key}</small><div class="amount">${money(values[key])}</div></article>`).join('');
const quantity = value => new Intl.NumberFormat('en-MY',{maximumFractionDigits:2}).format(Number(value||0));
const recordsIn = (records,start,end) => records.filter(row=>row.date>=start&&row.date<=end);

function showPage(name){ document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${name}`)); document.querySelectorAll('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.page===name)); }
document.querySelectorAll('.nav-button').forEach(button=>button.addEventListener('click',()=>showPage(button.dataset.page)));

function selectedRange(preset='month'){
  if(preset==='today') return {start:today,end:today,label:'Today'};
  if(preset==='yesterday'){const day=dateInMalaysia(-1);return {start:day,end:day,label:'Yesterday'};}
  return {start:monthStart,end:today,label:'This Month'};
}
state.selected=selectedRange();
$('#today-label').textContent=formatDate(today); $('#mtd-label').textContent=`${formatDate(monthStart)} – ${formatDate(today)}`;
$('#target-month-label').textContent=new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${monthStart}T00:00:00Z`));
$('#weekly-end').value=today; $('#weekly-start').value=dateInMalaysia(-6); $('#range-start').value=monthStart; $('#range-end').value=today; $('#target-month').value=today.slice(0,7);

function targetWarning(value){ const difference=value.sutera+value.eco-value.overall; if(value.overall===0||value.sutera===0||value.eco===0) return 'Warning: One or more targets are 0 (No Target).'; return Math.abs(difference)>.005?`Branch targets total ${money(value.sutera+value.eco)}, different from Overall Target ${money(value.overall)}.`:''; }
function renderCompletion(sales){ const target=targets.get(today.slice(0,7)); $('#completion-cards').innerHTML=['overall','sutera','eco'].map(scope=>{const current=scope==='overall'?sales.total:sales[scope], amount=target[scope], percentage=amount>0?current/amount*100:null;return `<article class="completion-card"><div class="completion-head"><small>${scope}</small><span class="completion-value">${money(current)}</span></div>${percentage===null?'<div class="no-target">No Target Set</div>':`<div class="percentage">${percentage.toFixed(2)}%</div><div class="progress" aria-label="${percentage.toFixed(2)} percent"><span style="width:${Math.min(100,Math.max(0,percentage))}%"></span></div><div class="branch-meta"><span>Target</span><strong>${money(amount)}</strong></div>`}</article>`}).join(''); $('#overview-target-warning').textContent=targetWarning(target); }
function renderOverview(records){ const todaySales=calculateSales(recordsIn(records,today,today)), mtd=calculateSales(recordsIn(records,monthStart,today)), range=calculateSales(recordsIn(records,state.selected.start,state.selected.end)); $('#today-cards').innerHTML=metricCards(todaySales); $('#mtd-cards').innerHTML=metricCards(mtd); $('#range-cards').innerHTML=metricCards(range); $('#range-label').textContent=`${state.selected.label}: ${formatDate(state.selected.start)} – ${formatDate(state.selected.end)}`; renderCompletion(mtd); }

async function refreshOverview(){
  const button=$('#refresh-sales'); button.disabled=true;
  const fetchStart=[monthStart,state.selected.start].sort()[0], fetchEnd=[today,state.selected.end].sort().at(-1);
  try{
    const data=await new DashboardDataService().readSales(fetchStart,fetchEnd); state.cache={records:data.records,range:{start:fetchStart,end:fetchEnd},at:new Date()};
    renderOverview(data.records); $('#freshness').className='status-strip live'; $('#freshness').textContent=`Updated · Last updated: ${formatTimestamp(state.cache.at)}`;
  }catch(error){
    if(state.cache&&state.cache.range.start<=fetchStart&&state.cache.range.end>=fetchEnd){ renderOverview(state.cache.records); $('#freshness').className='status-strip cached'; $('#freshness').textContent=`Cached · Last successful update: ${formatTimestamp(state.cache.at)} · Unable to refresh`; }
    else { $('#freshness').className='status-strip failed'; $('#freshness').textContent='Unable to sync data.'; ['#today-cards','#mtd-cards','#range-cards'].forEach(id=>$(id).innerHTML='<div class="empty-row">No data available for this period.</div>'); }
  }finally{button.disabled=false;}
}
$('#refresh-sales').addEventListener('click',refreshOverview);
document.querySelectorAll('[data-preset]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-preset]').forEach(x=>x.classList.remove('active'));button.classList.add('active');$('#range-form').classList.toggle('hidden',button.dataset.preset!=='custom');if(button.dataset.preset!=='custom'){state.selected=selectedRange(button.dataset.preset);refreshOverview();}}));
$('#range-form').addEventListener('submit',event=>{event.preventDefault();const start=$('#range-start').value,end=$('#range-end').value;if(start>end){$('#freshness').className='status-strip failed';$('#freshness').textContent='Failed · Start Date must be before End Date.';return;}state.selected={start,end,label:'Custom Range'};refreshOverview();});

function progressBlock(current,target,light=false){const percentage=target>0?current/target*100:null;if(percentage===null)return `<div class="no-target">No Target Set</div>`;return `<strong>${percentage.toFixed(2)}%</strong><div class="progress"><span style="width:${Math.min(100,Math.max(0,percentage))}%"></span></div><small>${money(current)} / ${money(target)}</small>`;}
function branchSalesCard(name,current,target){const percentage=target>0?current/target*100:null;return `<article class="branch-card"><h3>${name.toUpperCase()}</h3><div class="branch-amount">${money(current)}</div><div class="branch-meta"><span>Target</span><strong>${target>0?money(target):'No Target Set'}</strong></div><div class="branch-meta"><span>Completion</span><strong>${percentage===null?'—':percentage.toFixed(2)+'%'}</strong></div>${percentage===null?'':`<div class="progress"><span style="width:${Math.min(100,percentage)}%"></span></div>`}</article>`;}
function groupedSaleRows(records,type,branch){const groups=new Map();records.filter(row=>row.sale_type===type&&row.branch===branch&&Number(row.quantity)!==0).forEach(row=>{let name=String(row.product_name||row.package_type||'Other').trim()||'Other';if(name.toLowerCase()==='not_applicable')name=type==='package'?'Other Package':'Other Product';const current=groups.get(name)||{name,quantity:0,amount:0,staff:new Map()};current.quantity+=Number(row.quantity||0);current.amount+=Number(row.amount||0);for(const code of row.staff_codes||[]){const staff=current.staff.get(code)||{quantity:0,amount:0};staff.quantity+=Number(row.quantity||0)/Math.max(1,(row.staff_codes||[]).length);staff.amount+=Number(row.amount||0)/Math.max(1,(row.staff_codes||[]).length);current.staff.set(code,staff);}groups.set(name,current);});return [...groups.values()].sort((a,b)=>b.amount-a.amount||b.quantity-a.quantity);}
function saleDataSection(result,type){const source=result.sources.find(item=>item.name==='Pretty Sales'),records=source?.data?.records||[];return `<div class="data-branches">${['Sutera','Eco'].map(branch=>{const rows=groupedSaleRows(records,type,branch),total=result.totals.prettySales[type==='product'?'products':'packages'][branch.toLowerCase()];const staff=new Map();rows.forEach(row=>row.staff.forEach((value,code)=>{const current=staff.get(code)||{quantity:0,amount:0};current.quantity+=value.quantity;current.amount+=value.amount;staff.set(code,current);}));const leaders=[...staff.entries()].sort((a,b)=>b[1].amount-a[1].amount).slice(0,4);return `<article class="data-branch"><h3>${branch.toUpperCase()} <span>${quantity(total.quantity)} items · ${money(total.amount)}</span></h3><div class="responsive-table"><table><thead><tr><th>${type==='product'?'Product':'Package'}</th><th class="number">Qty</th>${type==='package'?'<th class="number">Amount</th>':''}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr><td>${escapeHtml(row.name)}</td><td class="number">${quantity(row.quantity)}</td>${type==='package'?`<td class="number">${money(row.amount)}</td>`:''}</tr>`).join(''):'<tr><td class="empty-row" colspan="3">No data available for this period.</td></tr>'}</tbody></table></div>${type==='package'&&leaders.length?`<p class="staff-summary"><strong>Staff:</strong> ${leaders.map(([code,value])=>`${escapeHtml(code)} ${quantity(value.quantity)} / ${money(value.amount)}`).join(' · ')}</p>`:''}</article>`;}).join('')}</div>`;}
function competitionSection(items){if(!items.length)return '<div class="empty-row">No competition data available for this period.</div>';const groups=new Map();items.forEach(item=>{const key=`${item.month}|${item.stage}|${item.rangeStart}|${item.rangeEnd}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(item);});const stageTitle={first:'First Stage',second:'Second Stage',month:'Monthly Summary'};return [...groups.entries()].map(([key,entries])=>{const [,stage,start,end]=key.split('|');return `<div class="stage-block"><div class="stage-header"><h3>${stageTitle[stage]}</h3><span class="stage-range">${formatDate(start)} – ${formatDate(end)}</span></div>${['product','package'].map(type=>`<div class="competition-category"><h4 class="category-title">${type==='product'?'Products Competition':'Packages Competition'}</h4><div class="competition-branches">${['Sutera','Eco'].map(branch=>{const entry=entries.find(item=>item.saleType===type&&item.branch===branch);return `<article class="competition-branch"><h4>${branch.toUpperCase()}</h4><p class="competition-result">Result: ${quantity(entry?.result.quantity)} · ${money(entry?.result.amount)}</p><div class="rank-table"><table><thead><tr><th>#</th><th>Staff</th><th class="number">Qty</th><th class="number">Amount</th></tr></thead><tbody>${entry?.ranking.length?entry.ranking.map(row=>`<tr><td class="rank-number">${row.rank}</td><td>${escapeHtml(row.staff)}</td><td class="number">${quantity(row.quantity)}</td><td class="number">${money(row.amount)}</td></tr>`).join(''):'<tr><td colspan="4" class="empty-row">No staff result</td></tr>'}</tbody></table></div></article>`;}).join('')}</div></div>`).join('')}</div>`;}).join('');}
function sourceState(source){const warnings=[...(source?.data?.missingSheets||[]),...(source?.data?.unreadableLayouts||[])];return source?.status==='failed'?'error':warnings.length?'warning':'ok';}
function dataStatusSection(result){const daily=result.sources.find(x=>x.name==='Daily Sales'),pretty=result.sources.find(x=>x.name==='Pretty Sales'),cuccio=result.sources.find(x=>x.name==='Cuccio'),birthday=result.sources.find(x=>x.name==='Birthday');const entries=[['Daily Sales',daily],['Pretty Sales',pretty],['Competition',pretty],['Products',pretty],['Packages',pretty],['Cuccio',cuccio],['Birthday',birthday]];const partial=entries.some(([,source])=>sourceState(source)!=='ok')||!result.validation.ok;return `<div class="status-grid">${entries.map(([name,source])=>`<div class="source-status ${sourceState(source)}">${name}</div>`).join('')}</div><p class="data-note ${partial?'warning':'ok'}">${partial?'Some data may be incomplete. Review Debug Details for the affected source.':'All dashboard data sources connected successfully.'}</p>`;}
function renderModule(module,result){const totals=result.totals,sameMonth=result.range.start.slice(0,7)===result.range.end.slice(0,7),target=sameMonth?targets.get(result.range.start.slice(0,7)):{overall:0,sutera:0,eco:0};let body='';
  if(module.id==='totalSales')body=`<div class="total-sales-feature"><div><span class="label">Combined Sales</span><div class="hero-amount">${money(totals.sales.total)}</div></div><div class="target-summary"><span class="label">Monthly Target</span>${sameMonth?progressBlock(totals.sales.total,target.overall,true):'<div class="no-target">Cross-month target is not combined</div>'}</div></div>`;
  else if(module.id==='branchSales')body=`<div class="branch-grid">${branchSalesCard('Sutera',totals.sales.sutera,target.sutera)}${branchSalesCard('Eco',totals.sales.eco,target.eco)}</div>`;
  else if(module.id==='targetCompletion')body=sameMonth?`<div class="completion-grid">${['overall','sutera','eco'].map(scope=>{const current=scope==='overall'?totals.sales.total:totals.sales[scope],value=target[scope],percentage=value>0?current/value*100:null;return `<article class="completion-card"><div class="completion-head"><small>${scope}</small><span class="completion-value">${money(current)}</span></div>${percentage===null?'<div class="no-target">No Target Set</div>':`<div class="percentage">${percentage.toFixed(2)}%</div><div class="progress"><span style="width:${Math.min(100,percentage)}%"></span></div><div class="branch-meta"><span>Target</span><strong>${money(value)}</strong></div>`}</article>`}).join('')}</div>`:'<p class="data-note warning">Target completion is not combined across different months.</p>';
  else if(module.id==='competition')body=competitionSection(totals.competition);
  else if(module.id==='products')body=saleDataSection(result,'product');
  else if(module.id==='packages')body=saleDataSection(result,'package');
  else if(module.id==='cuccio'||module.id==='birthday'){const values=totals[module.id];body=`<article class="kpi-card"><h3>${module.id.toUpperCase()}</h3><div class="kpi-values">${['sutera','eco','total'].map(scope=>`<div class="kpi-value ${scope==='total'?'total':''}"><small>${scope}</small><strong>${quantity(values[scope])}</strong></div>`).join('')}</div></article>`;}
  else if(module.id==='dataStatus')body=dataStatusSection(result);
  return `<section class="panel dashboard-section" data-module="${module.id}"><h2>${escapeHtml(module.title)}</h2>${body}</section>`;}
$('#weekly-form').addEventListener('submit',async event=>{event.preventDefault();const start=$('#weekly-start').value,end=$('#weekly-end').value,button=event.submitter||event.currentTarget.querySelector('button');$('#export-pdf').hidden=true;state.generatedRange=null;if(start>end){$('#weekly-message').className='status-strip failed';$('#weekly-message').textContent='Start Date must be before End Date.';return;}button.disabled=true;$('#weekly-message').className='status-strip neutral';$('#weekly-message').textContent='Loading dashboard data...';try{await loadCloudSettings([...new Set([start.slice(0,7),end.slice(0,7)])]);const result=await new DashboardDataService().syncWeekly(start,end);const modules=dashboardModules.configured(state.sectionSettings,result);$('#weekly-preview').innerHTML=`<div class="preview-shell"><header class="preview-header"><div><p class="eyebrow">PRETTY NAILS SPA</p><h2>Weekly Sales Dashboard</h2><p>Consolidated branch performance</p></div><div class="preview-period">${formatDate(start)} – ${formatDate(end)}</div></header>${modules.map(module=>renderModule(module,result)).join('')}</div>`;$('#raw-data').textContent=JSON.stringify(result,null,2);state.generatedRange={start,end};$('#export-pdf').hidden=false;const failed=result.sources.filter(x=>x.status==='failed');$('#weekly-message').className=`status-strip ${failed.length?'cached':'live'}`;$('#weekly-message').textContent=failed.length?'Some data may be incomplete. See Data Status.':`Updated · Last updated: ${formatTimestamp(new Date())}`;}catch(error){$('#weekly-message').className='status-strip failed';$('#weekly-message').textContent='Unable to sync data.';$('#weekly-preview').innerHTML='<div class="empty-state"><span>!</span><h2>Dashboard unavailable</h2><p>Please retry in a moment.</p></div>';}finally{button.disabled=false;}});
$('#export-pdf').addEventListener('click',()=>{if(!state.generatedRange)return;openPrintDialog(state.generatedRange);});
$('#export-pdf').title='For best PDF results: A4 · Landscape · Background graphics ON';

function loadTargetForm(){const value=targets.get($('#target-month').value);['overall','sutera','eco'].forEach(scope=>$(`#target-${scope}`).value=value[scope]);$('#target-warning').textContent=targetWarning(value);}
$('#target-month').addEventListener('change',loadTargetForm); ['overall','sutera','eco'].forEach(scope=>$(`#target-${scope}`).addEventListener('input',()=>$('#target-warning').textContent=targetWarning(Object.fromEntries(['overall','sutera','eco'].map(x=>[x,Number($(`#target-${x}`).value)])))));
$('#target-form').addEventListener('submit',async event=>{event.preventDefault();$('#target-save-status').textContent='Saving…';try{const month=$('#target-month').value, value=Object.fromEntries(['overall','sutera','eco'].map(x=>[x,Number($(`#target-${x}`).value)]));await saveTargets(month,value);targets.save(month,value);$('#target-warning').textContent=targetWarning(value);$('#target-save-status').textContent='Saved to Cloud.';if(month===today.slice(0,7)&&state.cache)renderOverview(state.cache.records);}catch(error){$('#target-save-status').textContent=error.message;}});
function renderSectionSettings(){state.sectionSettings.sort((a,b)=>a.order-b.order);$('#section-settings').innerHTML=state.sectionSettings.map((item,index)=>`<div class="section-setting" data-id="${item.id}"><input type="checkbox" ${item.enabled?'checked':''} aria-label="Show ${escapeHtml(item.title)}"><input type="text" value="${escapeHtml(item.title)}" aria-label="Display title"><button data-move="up" ${index===0?'disabled':''}>↑ Up</button><button data-move="down" ${index===state.sectionSettings.length-1?'disabled':''}>↓ Down</button></div>`).join('');}
$('#section-settings').addEventListener('click',event=>{const direction=event.target.dataset.move;if(!direction)return;state.sectionSettings=[...document.querySelectorAll('.section-setting')].map((row,index)=>({id:row.dataset.id,enabled:row.querySelector('[type=checkbox]').checked,title:row.querySelector('[type=text]').value,order:(index+1)*10}));const id=event.target.closest('[data-id]').dataset.id,index=state.sectionSettings.findIndex(x=>x.id===id),next=direction==='up'?index-1:index+1;[state.sectionSettings[index],state.sectionSettings[next]]=[state.sectionSettings[next],state.sectionSettings[index]];state.sectionSettings.forEach((x,i)=>x.order=(i+1)*10);renderSectionSettings();});
$('#save-sections').addEventListener('click',async()=>{try{state.sectionSettings=[...document.querySelectorAll('.section-setting')].map((row,index)=>({id:row.dataset.id,enabled:row.querySelector('[type=checkbox]').checked,title:row.querySelector('[type=text]').value.trim()||dashboardModules.get(row.dataset.id).title,order:(index+1)*10}));await saveSectionSettings(state.sectionSettings);state.sectionSettings=sections.save(state.sectionSettings);renderSectionSettings();$('#section-save-status').textContent='Saved to Cloud.';}catch(error){$('#section-save-status').textContent=error.message;}});

async function loadCloudSettings(months){
  try{
    const result=await readPublicSettings(months);
    for(const month of months){const rows=(result.targets||[]).filter(row=>row.year_month===month), value={overall:0,sutera:0,eco:0};rows.forEach(row=>value[row.scope]=Number(row.amount));targets.save(month,value);}
    if(result.sections?.length){state.sectionSettings=result.sections.map(row=>({id:row.section_id,title:row.display_title,enabled:row.enabled,order:row.display_order}));sections.save(state.sectionSettings);renderSectionSettings();}
    state.settingsSource='cloud'; return true;
  }catch(error){state.settingsSource='cache';$('#auth-message').textContent=`Cloud Settings unavailable; cached settings shown. ${error.message}`;return false;}
}
async function renderAdminSession(){
  const {data:{session}}=await supabase.auth.getSession();
  let admin=false;
  if(session){try{await requireAdmin();admin=true;}catch(error){$('#admin-status').textContent=error.message;}}
  $('#admin-settings').hidden=!admin;$('#admin-login-button').hidden=admin;$('#admin-logout-button').hidden=!session;$('#admin-email').disabled=admin;$('#admin-password').disabled=admin;
  if(admin){$('#admin-status').textContent=`Admin connected: ${session.user.email}`;$('#password-reset-form').hidden=true;}
}
$('#admin-login-form').addEventListener('submit',async event=>{event.preventDefault();$('#admin-status').textContent='Signing in…';const {error}=await supabase.auth.signInWithPassword({email:$('#admin-email').value.trim(),password:$('#admin-password').value});$('#admin-password').value='';if(error){$('#admin-status').textContent='Unable to sign in';return;}$('#password-reset-form').hidden=true;await renderAdminSession();});
$('#admin-forgot-button').addEventListener('click',async()=>{const email=$('#admin-email').value.trim();if(!email){$('#admin-status').textContent='Enter the Admin email first.';return;}$('#admin-status').textContent='Sending recovery email…';const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}${window.location.pathname}`});$('#admin-status').textContent=error?'Unable to send password recovery email.':'Password recovery email sent. Open the newest email on this device.';});
$('#password-reset-form').addEventListener('submit',async event=>{event.preventDefault();const password=$('#new-admin-password').value,confirm=$('#confirm-admin-password').value;if(password!==confirm){$('#password-reset-status').textContent='Passwords do not match.';return;}const {error}=await supabase.auth.updateUser({password});$('#new-admin-password').value='';$('#confirm-admin-password').value='';if(error){$('#password-reset-status').textContent='Unable to update password.';return;}$('#password-reset-status').textContent='Password updated successfully.';$('#password-reset-form').hidden=true;history.replaceState({},document.title,`${location.origin}${location.pathname}`);await renderAdminSession();});
$('#admin-logout-button').addEventListener('click',async()=>{await supabase.auth.signOut();$('#admin-status').textContent='Signed out.';await renderAdminSession();});
supabase.auth.onAuthStateChange((event)=>{const recoveryLink=location.hash.includes('type=recovery')||location.search.includes('type=recovery');if(event==='PASSWORD_RECOVERY'&&recoveryLink){$('#password-reset-form').hidden=false;showPage('settings');}setTimeout(renderAdminSession,0);});
renderSectionSettings();loadTargetForm();renderOverview([]);await loadCloudSettings([today.slice(0,7)]);loadTargetForm();await renderAdminSession();await refreshOverview();
